### ISSUE TITLE
from_rows (0.22.0)

### ISSUE THREAD

**Issue by jeprojects** [twistedfall/serde_rusqlite#5]
In version 0.21.0 I was doing this:

`let rows = from_rows::<Blog>(stmt.query(NO_PARAMS)?).collect::<Vec<_>>();`

In version 0.22.0 it returns a result for each row, how is it best to now collect into the Vec<Blog> ?

**Comment by twistedfall** [comment]
Iterators now return `Result<T>` instead of just `T` to be able to propagate errors from `rusqlite`. So the simple solution would be to additionally `.map(|x| x.unwrap())` before `collect()` or better collect into `Result<Vec<Blog>, ...>`. Full changelog is in the commit message: https://github.com/twistedfall/serde_rusqlite/commit/345cc346fa55d622bceb01ad3447546e5b429757
